spring:
  application:
    name: stiky-api
  profiles:
    active: prod # 기본값

  # Flyway 설정 (DB 스키마 자동 관리)
  flyway:
    enabled: true
    baseline-on-migrate: true # 기존 DB가 있어도 마이그레이션 실행

springdoc:
  swagger-ui:
    url: /docs/openapi3.yaml
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha